export const BODY_COMPOSITION_SYSTEM_PROMPT =
  "You extract structured data from a Body Composition Analysis Report in JSON.";

export const BODY_COMPOSITION_SCHEMA_HINT = [
  "Return ONLY valid JSON. Do not include markdown.",
  "Extract values from the body composition report and fill what you can; use null if missing.",
  "Use numbers (not strings) for numeric values.",
  "",
  "Return JSON with this structure:",
  "{",
  '  "requestId": string,',
  '  "report": {',
  '    "title": string|null,',
  '    "deviceCode": string|null,',
  '    "brand": string|null,',
  '    "person": { "id": string|null, "heightCm": number|null, "age": number|null, "gender": string|null, "testDateTime": string|null },',
  '    "score": number|null,',
  '    "bodyComposition": {',
  '      "totalBodyWater": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '      "protein": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '      "mineral": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '      "bodyFatMass": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '      "summary": {',
  '        "totalBodyWater": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '        "softLeanMass": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '        "fatFreeMass": { "value": number|null, "unit": string|null, "rangeText": string|null },',
  '        "weight": { "value": number|null, "unit": string|null, "rangeText": string|null }',
  "      }",
  "    },",
  '    "muscleFatAnalysis": {',
  '      "weightKg": number|null,',
  '      "skeletalMuscleMassKg": number|null,',
  '      "bodyFatMassKg": number|null',
  "    },",
  '    "obesityAnalysis": {',
  '      "bmi": number|null,',
  '      "percentBodyFat": number|null,',
  '      "waistHipRatio": number|null,',
  '      "obesityRate": number|null,',
  '      "bmiClass": string|null,',
  '      "pbfClass": string|null',
  "    },",
  '    "weightControl": {',
  '      "targetWeightKg": number|null,',
  '      "weightControlKg": number|null,',
  '      "fatControlKg": number|null,',
  '      "muscleControlKg": number|null',
  "    },",
  '    "segmentalLean": {',
  '      "rightArm": { "kg": number|null, "pct": number|null },',
  '      "leftArm": { "kg": number|null, "pct": number|null },',
  '      "trunk": { "kg": number|null, "pct": number|null },',
  '      "rightLeg": { "kg": number|null, "pct": number|null },',
  '      "leftLeg": { "kg": number|null, "pct": number|null }',
  "    },",
  '    "segmentalMuscle": {',
  '      "rightArmKg": number|null, "rightArmPct": number|null, "leftArmKg": number|null, "leftArmPct": number|null, "trunkKg": number|null, "trunkPct": number|null, "rightLegKg": number|null, "rightLegPct": number|null, "leftLegKg": number|null, "leftLegPct": number|null',
  "    },",
  '    "segmentalFat": {',
  '      "rightArmKg": number|null, "rightArmPct": number|null, "leftArmKg": number|null, "leftArmPct": number|null, "trunkKg": number|null, "trunkPct": number|null, "rightLegKg": number|null, "rightLegPct": number|null, "leftLegKg": number|null, "leftLegPct": number|null',
  "    },",
  '    "research": { "basalMetabolicRateKcal": number|null, "visceralFatArea": number|null },',
  '    "impedance": {',
  '      "freq50kHz": { "rightArm": number|null, "leftArm": number|null, "trunk": number|null, "rightLeg": number|null, "leftLeg": number|null },',
  '      "freq250kHz": { "rightArm": number|null, "leftArm": number|null, "trunk": number|null, "rightLeg": number|null, "leftLeg": number|null }',
  "    }",
  "  }",
  "}"
].join("\n");
