export const CARDIAC_INVESTIGATIONS_SYSTEM_PROMPT = [
  "You are a senior cardiologist AI and medical report extraction engine.",
  "You will receive one or more cardiac investigation documents: ECG images/reports, echocardiogram (ECHO) reports,",
  "treadmill test (TMT) reports, CT coronary calcium score (CAC) reports, CT coronary angiogram (CTCA) reports,",
  "and/or invasive coronary angiogram (CAG) reports.",
  "",
  "Extract all medical parameters that are actually present in the uploaded documents and images.",
  "Only extract values that are explicitly visible or stated in the document — do not hallucinate or infer.",
  "If a parameter is absent from the document, do not include it — omit it entirely rather than setting it to null.",
  "Map every extracted value to the closest matching field in the output schema.",
  "Any parameter present in the document that does not match a schema field must go into otherFindings as plain text.",
  "If multiple documents are uploaded, extract from every document — do not stop after the first.",
  "Return ONLY valid JSON. No markdown fences. No commentary.",
  "For document sections (ecg, echo, tmt, cac, ctCoronaryAngiogram, cag): include only those where a matching document was found.",
  "For the riskScores section: ALWAYS include it. Populate from the documents if scores are printed; otherwise estimate from extracted findings and patient info.",
  "Use 'yes' or 'no' (lowercase strings) for boolean/yes-no fields."
].join("\n");

export const CARDIAC_INVESTIGATIONS_SCHEMA_HINT = `{
  "ecg": {
    "hr": null,
    "pInterval": null,
    "prInterval": null,
    "qrsDuration": null,
    "qtInterval": null,
    "qtcBz": null,
    "pAxis": null,
    "qrsAxis": null,
    "tAxis": null,
    "rv5": null,
    "sv1": null,
    "rv5sv1Sum": null,
    "rhythm": "",
    "isNormal": "yes",
    "summary": "",
    "atrialFibrillation": "no",
    "lvh": "no",
    "stDepressionOrTInversion": "no",
    "qtProlongation": "no",
    "bundleBranchBlock": "no",
    "bundleBranchBlockType": "",
    "pathologicalQWaves": "no",
    "wpwPattern": "no",
    "sinusTachycardia": "no",
    "sinusBradycardia": "no",
    "firstDegreeAvBlock": "no",
    "atrialFlutter": "no",
    "ventriularExtrasystoles": "no",
    "atrialExtrasystoles": "no",
    "otherFindings": ""
  },
  "echo": {
    "ef": null,
    "fs": null,
    "edv": null,
    "esv": null,
    "strokeVolume": null,
    "cardiacOutput": null,
    "lvMassGrams": null,
    "lvMassIndex": null,

    "lvedd": null,
    "lvesd": null,
    "ivsd": null,
    "ivss": null,
    "pwt": null,
    "lvpws": null,
    "rvidd": null,
    "aorticRoot": null,
    "laSize": null,
    "laVolume": null,
    "aoLaRatio": null,
    "avCupOpening": null,
    "epss": null,
    "efSlope": null,
    "de": null,

    "mvEVelocity": null,
    "mvAVelocity": null,
    "mvEaRatio": null,
    "avVelocity": null,
    "avGradient": null,
    "tvEVelocity": null,
    "tvAVelocity": null,
    "pvVelocity": null,

    "mrPresent": "no",
    "mrSeverity": "",
    "arPresent": "no",
    "arSeverity": "",
    "trPresent": "no",
    "trSeverity": "",
    "prPresent": "no",
    "prSeverity": "",

    "tapse": null,
    "ivcSize": null,
    "ivcCollapsibility": "",

    "leftVentricleDescription": "",
    "leftAtriumDescription": "",
    "rightVentricleDescription": "",
    "rightAtriumDescription": "",
    "ivsIas": "",
    "aortaPA": "",
    "systemicPulmonaryVeins": "",

    "lvHypertrophy": "no",
    "leftAtrialEnlargement": "no",
    "diastolicDysfunctionGrade": null,
    "pulmonaryPressure": null,
    "wallMotionAbnormality": "no",
    "wallMotionDetails": "",
    "pericardialEffusion": "no",
    "clotMassVegetation": "no",
    "isNormal": "yes",
    "summary": "",
    "otherFindings": ""
  },
  "tmt": {
    "result": "negative",
    "protocol": "",
    "exerciseDuration": "",
    "mets": null,
    "maxHeartRate": null,
    "targetHeartRate": null,
    "targetHeartRateAchieved": "yes",
    "percentTargetHeartRate": null,
    "restingSbp": null,
    "restingDbp": null,
    "peakSbp": null,
    "peakDbp": null,
    "stChanges": "",
    "stDepression": null,
    "stElevation": null,
    "symptoms": "",
    "reasonForStopping": "",
    "dukeTreadmillScore": null,
    "ecgChanges": "",
    "conclusion": "",
    "summary": ""
  },
  "cac": {
    "cacScore": null,
    "riskCategory": "",
    "percentile": "",
    "volumeScore": null,
    "ladScore": null,
    "lcxScore": null,
    "rcaScore": null,
    "lmainScore": null,
    "conclusion": "",
    "summary": ""
  },
  "ctCoronaryAngiogram": {
    "lmain": "",
    "lad": "",
    "lcx": "",
    "rca": "",
    "diagonals": "",
    "om": "",
    "ramus": "",
    "maxStenosisPercent": null,
    "significantStenosis": "no",
    "plaque": "",
    "plaqueType": "",
    "dominance": "",
    "isNormal": "yes",
    "ctssScore": null,
    "conclusion": "",
    "summary": ""
  },
  "cag": {
    "lmain": "",
    "lad": "",
    "lcx": "",
    "rca": "",
    "diagonals": "",
    "om": "",
    "ramus": "",
    "ef": null,
    "vesselDisease": "",
    "dominance": "",
    "significantStenosis": "no",
    "lvgramFindings": "",
    "recommendation": "",
    "isNormal": "yes",
    "conclusion": "",
    "summary": ""
  },
  "riskScores": {
    "qrisk3": {
      "yourRisk": null,
      "averageRisk": null
    },
    "prevent": {
      "heartAttackYourRisk": null,
      "heartAttackOptimalRisk": null,
      "strokeYourRisk": null,
      "strokeOptimalRisk": null,
      "heartFailureYourRisk": null,
      "heartFailureOptimalRisk": null
    },
    "preventDiabetics": {
      "chdYourScore": null,
      "chdOptimalScore": null,
      "strokeYourScore": null,
      "strokeOptimalScore": null
    },
    "heartAge": {
      "yourAge": null,
      "heartAge": null
    }
  }
}`;

export function buildCardiacInvestigationsUserPrompt({ extractedText, patientAge, patientSex, patientDiabetic }) {
  const patientContext = [];
  if (patientAge) patientContext.push(`Patient age: ${patientAge} years`);
  if (patientSex) patientContext.push(`Patient sex: ${patientSex}`);
  patientContext.push(`Patient is diabetic: ${patientDiabetic ? "yes" : "no"}`);

  return [
    "Analyze ALL cardiac investigation documents provided (images and/or text below).",
    "Extract all medical parameters that are actually present in the documents and images.",
    "Do not extract any parameter that is absent from the documents — only include what is explicitly visible or stated.",
    "",
    patientContext.length > 0 ? `Patient information:\n${patientContext.join("\n")}` : "",
    "",
    "Return JSON strictly matching this schema (include only sections where documents were found):",
    CARDIAC_INVESTIGATIONS_SCHEMA_HINT,
    "",
    "Store numeric values without units. Use 'yes' or 'no' for boolean findings.",
    "Map each extracted value to the closest schema field.",
    "Anything present in the document that has no matching schema field goes into otherFindings as plain text.",
    "",
    "IMPORTANT — riskScores section (ALWAYS return this section):",
    "  - Always return riskScores in the JSON output, even if documents do not contain them.",
    "  - If QRISK3, PREVENT, or Heart Age values are explicitly printed in the documents, extract them exactly.",
    "  - If they are NOT printed, use the patient age, sex, and all extracted cardiac findings (ECG, ECHO, TMT, CAC, BP, lipids, etc.) to calculate or estimate them as a senior cardiologist would.",
    "  - heartAge.yourAge must always equal the patient age provided above (if given).",
    "  - heartAge.heartAge: estimate the patient's cardiac/heart age based on their risk profile.",
    "  - qrisk3.yourRisk: 10-year cardiovascular risk percentage (QRISK3 algorithm).",
    "  - qrisk3.averageRisk: average 10-year CVD risk for a healthy person of the same age and sex.",
    "  - prevent.heartAttackYourRisk / strokeYourRisk / heartFailureYourRisk: 10-year risks (PREVENT equations).",
    "  - prevent.*OptimalRisk: optimal risk for a healthy person of the same age and sex.",
    "  - preventDiabetics: populate ONLY if patient is diabetic (see patient info above); if patient is NOT diabetic, omit the preventDiabetics section entirely.",
    "  - Store all percentage values as plain numbers without the % symbol (e.g. 12 for 12%).",
    "",
    "Text extracted from uploaded documents (may be empty if only images were provided):",
    typeof extractedText === "string" ? extractedText : ""
  ].filter(line => line !== null && line !== undefined).join("\n");
}
